language: python
python:
  - "2.7"
  - "3.6"
sudo: false
virtualenv:
  system_site_packages: true
before_install:
  - pip install openpyxl fastnumbers json_tricks nilearn nibabel scipy numpy pandas scikit-learn
script: nosetests testcases/*.py

