language: python
python:
  - "2.7"
sudo: false
virtualenv:
  system_site_packages: true
before_install:
  - pip install openpyxl fastnumbers json_tricks nilearn nibabel scipy numpy pandas
script: nosetests testcases/*.py

