language: python
python:
  - "2.7"
sudo: false
virtualenv:
  system_site_packages: true
before_install:
  - pip install openpyxl
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
script: nosetests testcases/*.py
